### ISSUE TITLE
How to implement chat

### ISSUE THREAD

**Issue by TestOSI** [apizee/ApiRTC-ionic#17]
I want to implement chat feature along with video call, can you tell the procedure

**Comment by AmrAlmagic** [comment]
you can follow the [documentation](https://dev.apirtc.com/reference/Session.html).

**Comment by FredLuart** [comment]
Hello, You can check our [tutorial page](https://dev.apirtc.com/tutorials/index)
And for instance [Conversation-13](https://dev.apirtc.com/tutorials/conferencing/conf_chat_file) that demonstrate video conference + chat + file transfer.
