### ISSUE TITLE
Blue Video Call and shake top to bottom

### ISSUE THREAD

**Issue by AmrAlmagic** [apizee/ApiRTC-ionic#18]
I use  [V3 ](https://dev.apirtc.com/apiRTC_V3/module-ApiRTC.html), Ionic 3, and Cordova 8.

while making a video call for some android devices my stream video color is blue !! and the video shake top and bottom also happens for the remote stream then stops form streaming correctly (very late).

**Comment by sachakh** [comment]
This sample requires apiRTC 4+, Ionic 5+
