### ISSUE TITLE
Android error

### ISSUE THREAD

**Issue by fjoalland** [apizee/ApiRTC-ionic#6]
I'm trying to call my laptop from my Android device, they are both on the same wifi.
When I call my laptop form my device, I have this bug:

> [22:48:32]  console.error: [2018-05-19T20:48:33.597Z] [ERROR] apiRTC : Failed to get access to local media. Error code
            was undefined
[22:48:32]  console.error: [2018-05-19T20:48:33.598Z] [ERROR] apiRTC [object Object]

And when I call my device from my laptop, the button "call" of my device is red but it doesn't"t work =.

**Comment by fjoalland** [comment]
I think the problem is because I need HTTPS. Do you know if I'm in a good way?

**Comment by krngd2** [comment]
May be you need

>  ionic cordova plugin add cordova-plugin-media

**Comment by TaiJinYuan** [comment]
Same issue, here.
Please help me if anyone solved this.
I tested on android device but found the following error.

> 10-04 10:54:09.176 14529-5396/? E/fb4a.FacebookPushServerRegistrar: RegisterPushToken register_push failed CONNECTION_FAILURE: CONNECTION_FAILURE
Thanks in advance.

**Comment by fjoalland** [comment]
You need to be in HTTPS
