### ISSUE TITLE
iOS can't launch

### ISSUE THREAD

**Issue by videmort** [apizee/ApiRTC-ionic#7]
Hi 
i'm getting this error every time

'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/B8152C85-0FE9-47B1-8DDD-F3B072A8EB88/ApiRTC.app> (loaded)' with name 'NSMainNibFile~ipad''

Any idea?

**Comment by AmrAlmagic** [comment]
try follow this guide for[ iostrc plugin](https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/blob/master/docs/Building.md)
